### ISSUE TITLE
Unable to access verification v4.4

### ISSUE THREAD

**Issue by Roei639** [labbots/google-drive-upload#190]
1. Connects through a terminal by pressing gupload xxxx.json
2. Info: Account names can only contain alphabets / numbers / dashes.
3. Tap a backup name
4. Refresh Token - enter
5. Visit the below URL, follow the instructions and then come back to commandline
6. Opening a Chrome browser and copying a link
Error:
This site cannot be accessed
 Could not connect to localhost.
 You should try:
 check the connection
 ERR_CONNECTION_REFUSED

**Comment by Akianonymus** [comment]
Have you tried this script ?

https://raw.githubusercontent.com/Akianonymus/google-drive-upload/master/release/bash/gupload

If still not solved, then run with -D flag and send logs

**Comment by Roei639** [comment]
Doesn't work in the script you sent
I can't access localhost through the terminal
Is it possible?  Why does it point to localhost?

**Comment by Roei639** [comment]
Debug:
```
pi@raspberrypi:~ $ gupload gupload.json -D
+ PS4='-> '
-> '[' -n '' ']'
-> '[' -n '' ']'
-> mkdir -p /home/pi/.google-drive-upload
-> '[' -n '' ']'
-> '[' -n '' ']'
-> '[' -z gupload.json ']'
-> '[' -z '' ']'
-> case "${SKIP_DUPLICATES:-$OVERWRITE}" in
-> :
-> return 0
-> _check_internet
-> : justify 'Checking Internet Connection..' -
-> _timeout 10 curl -Is google.com --compressed
-> timeout_timeout=10
-> shift
-> _clear_line 1
-> :
--> command -v mktemp
--> mktemp -u
-> TMPFILE=/tmp/tmp.UO1kBa69T4
-> export TMPFILE
-> _setup_traps
-> export SUPPORT_ANSI_ESCAPES TMPFILE ACCESS_TOKEN ACCESS_TOKEN_EXPIRY INITIAL_ACCESS_TOKEN ACCOUNT_NAME CONFIG ACCESS_TOKEN_SERVICE_PID
-> trap 'abnormal_exit="1" ; exit' INT TERM
-> trap _cleanup EXIT
-> trap '' TSTP
-> export MAIN_PID=11752
-> MAIN_PID=11752
-> : justify 'Checking credentials..' -
-> _check_credentials
-> export CONFIG CONFIG_INFO DEFAULT_ACCOUNT NEW_ACCOUNT_NAME CUSTOM_ACCOUNT_NAME
QUIET COUNT
-> _reload_config
-> export CONFIG
-> '[' -r /home/pi/.googledrive.conf ']'
-> _parse_config /home/pi/.googledrive.conf
-> _config_file_parse_config=/home/pi/.googledrive.conf
-> print_parse_config=false
-> '[' -r /home/pi/.googledrive.conf ']'
-> IFS==
-> read -r key val
-> '[' -n ACCOUNT_backup_CLIENT_ID ']'
-> '[' -n '"903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com"' ']'
-> '[' -n ACCOUNT_backup_CLIENT_ID ']'
-> key=ACCOUNT_backup_CLIENT_ID
-> val='"903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com"'
-> key=ACCOUNT_backup_CLIENT_ID
-> val='"903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com"'
-> case "$val" in
-> val='903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com"'-> val=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> export ACCOUNT_backup_CLIENT_ID=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> '[' false = true ']'
-> IFS==
-> read -r key val
-> '[' -n ACCOUNT_backup_CLIENT_SECRET ']'
-> '[' -n '"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"' ']'
-> '[' -n ACCOUNT_backup_CLIENT_SECRET ']'
-> key=ACCOUNT_backup_CLIENT_SECRET
-> val='"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"'
-> key=ACCOUNT_backup_CLIENT_SECRET
-> val='"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"'
-> case "$val" in
-> val='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"'
-> val=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
-> export ACCOUNT_backup_CLIENT_SECRET=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
-> '[' false = true ']'
-> IFS==
-> read -r key val
-> return 0
-> return 0
-> _handle_old_config
-> export CLIENT_ID CLIENT_SECRET REFRESH_TOKEN ROOT_FOLDER ROOT_FOLDER_NAME
-> '[' -n '' ']'
-> return 0
-> ACCOUNT_NAME=
-> '[' -n '' ']'
-> '[' -n '' ']'
-> '[' -n '' ']'
-> UPDATE_DEFAULT_ACCOUNT=_update_config
-> '[' -z '' ']'
-> _all_accounts
-> '[' 0 -gt 0 ']'
-> _set_new_account_name ''
-> export QUIET NEW_ACCOUNT_NAME
-> _reload_config
-> export CONFIG
-> '[' -r /home/pi/.googledrive.conf ']'
-> _parse_config /home/pi/.googledrive.conf
-> _config_file_parse_config=/home/pi/.googledrive.conf
-> print_parse_config=false
-> '[' -r /home/pi/.googledrive.conf ']'
-> IFS==
-> read -r key val
-> '[' -n ACCOUNT_backup_CLIENT_ID ']'
-> '[' -n '"903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com"' ']'
-> '[' -n ACCOUNT_backup_CLIENT_ID ']'
-> key=ACCOUNT_backup_CLIENT_ID
-> val='"903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com"'
-> key=ACCOUNT_backup_CLIENT_ID
-> val='"903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com"'
-> case "$val" in
-> val='903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com"'-> val=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> export ACCOUNT_backup_CLIENT_ID=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> '[' false = true ']'
-> IFS==
-> read -r key val
-> '[' -n ACCOUNT_backup_CLIENT_SECRET ']'
-> '[' -n '"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"' ']'
-> '[' -n ACCOUNT_backup_CLIENT_SECRET ']'
-> key=ACCOUNT_backup_CLIENT_SECRET
-> val='"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"'
-> key=ACCOUNT_backup_CLIENT_SECRET
-> val='"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"'
-> case "$val" in
-> val='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"'
-> val=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
-> export ACCOUNT_backup_CLIENT_SECRET=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
-> '[' false = true ']'
-> IFS==
-> read -r key val
-> return 0
-> return 0
-> new_account_name_set_new_account_name=
-> unset name_valid_set_new_account_name
-> '[' -z '' ']'
-> _all_accounts
-> _print_center normal ' New account name: ' =
-> '[' 3 = 3 ']'
-> printf '%s\n' ' New account name: '
 New account name:
-> _print_center normal 'Info: Account names can only contain alphabets / numbers
/ dashes.' ' '
-> '[' 3 = 3 ']'
-> printf '%s\n' 'Info: Account names can only contain alphabets / numbers / dashes.'
Info: Account names can only contain alphabets / numbers / dashes.
-> printf '\n'
-> '[' -n '' ']'
-> '[' -n '' ']'
-> '[' -t 1 ']'
-> printf -- '-> \033[?7l'
-> -> read -r new_account_name_set_new_account_name
backup
-> printf '\033[?7h'
-> _clear_line 1
-> :
-> '[' -n '' ']'
-> '[' -n backup ']'
-> _account_name_valid backup
-> name_account_name_valid=backup
-> account_name_regex_account_name_valid='^([A-Za-z0-9_])+$'
-> _assert_regex '^([A-Za-z0-9_])+$' backup
-> declare 'pattern=^([A-Za-z0-9_])+$' string=backup
-> [[ backup =~ ^([A-Za-z0-9_])+$ ]]
-> return 0
-> return 0
-> _account_exists backup
-> name_account_exists=backup
-> client_id_account_exists=
-> client_secret_account_exists=
-> refresh_token_account_exists=
-> _account_name_valid backup
-> name_account_name_valid=backup
-> account_name_regex_account_name_valid='^([A-Za-z0-9_])+$'
-> _assert_regex '^([A-Za-z0-9_])+$' backup
-> declare 'pattern=^([A-Za-z0-9_])+$' string=backup
-> [[ backup =~ ^([A-Za-z0-9_])+$ ]]
-> return 0
-> return 0
-> _set_value indirect client_id_account_exists ACCOUNT_backup_CLIENT_ID
-> case "${1:?}" in
-> eval export 'client_id_account_exists="$ACCOUNT_backup_CLIENT_ID"'
--> export client_id_account_exists=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
--> client_id_account_exists=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> _set_value indirect client_secret_account_exists ACCOUNT_backup_CLIENT_SECRET
-> case "${1:?}" in
-> eval export 'client_secret_account_exists="$ACCOUNT_backup_CLIENT_SECRET"'
--> export client_secret_account_exists=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
--> client_secret_account_exists=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
-> _set_value indirect refresh_token_account_exists ACCOUNT_backup_REFRESH_TOKEN
-> case "${1:?}" in
-> eval export 'refresh_token_account_exists="$ACCOUNT_backup_REFRESH_TOKEN"'
--> export refresh_token_account_exists=
--> refresh_token_account_exists=
-> '[' -z '' ']'
-> return 1
-> export new_account_name_set_new_account_name=backup NEW_ACCOUNT_NAME=backup
-> new_account_name_set_new_account_name=backup
-> NEW_ACCOUNT_NAME=backup
-> name_valid_set_new_account_name=true
-> continue
-> '[' -n true ']'
-> _print_center normal ' Given account name: backup ' =
-> '[' 3 = 3 ']'
-> printf '%s\n' ' Given account name: backup '
 Given account name: backup
-> export ACCOUNT_NAME=backup
-> ACCOUNT_NAME=backup
-> return 0
-> _check_account_credentials backup
-> account_name_check_account_credentials=backup
-> _check_client ID backup
-> export CONFIG QUIET
-> type_check_client=CLIENT_ID
-> account_name_check_client=backup
-> unset type_value_check_client type_name_check_client valid_check_client client_check_client message_check_client regex_check_client
-> '[' CLIENT_ID = CLIENT_ID ']'
-> regex_check_client='[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com'
-> type_name_check_client=ACCOUNT_backup_CLIENT_ID
-> _set_value indirect type_value_check_client ACCOUNT_backup_CLIENT_ID
-> case "${1:?}" in
-> eval export 'type_value_check_client="$ACCOUNT_backup_CLIENT_ID"'
--> export type_value_check_client=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
--> type_value_check_client=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> '[' -n 903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com ']'
-> '[' -n '' ']'
-> '[' -n 903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com ']'
-> _assert_regex '[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com' 903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> declare 'pattern=[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com' string=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> [[ 903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com =~
[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com ]]
-> return 0
-> '[' -n '' ']'
-> valid_check_client=true
-> continue
-> '[' -n 903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com ']'
-> '[' -n true ']'
-> _set_value direct ACCOUNT_backup_CLIENT_ID 903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> case "${1:?}" in
-> export ACCOUNT_backup_CLIENT_ID=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> ACCOUNT_backup_CLIENT_ID=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> _set_value direct CLIENT_ID 903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> case "${1:?}" in
-> export CLIENT_ID=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> CLIENT_ID=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com
-> return 0
-> _check_client SECRET backup
-> export CONFIG QUIET
-> type_check_client=CLIENT_SECRET
-> account_name_check_client=backup
-> unset type_value_check_client type_name_check_client valid_check_client client_check_client message_check_client regex_check_client
-> '[' CLIENT_SECRET = CLIENT_ID ']'
-> regex_check_client='[0-9A-Za-z_-]+'
-> type_name_check_client=ACCOUNT_backup_CLIENT_SECRET
-> _set_value indirect type_value_check_client ACCOUNT_backup_CLIENT_SECRET
-> case "${1:?}" in
-> eval export 'type_value_check_client="$ACCOUNT_backup_CLIENT_SECRET"'
--> export type_value_check_client=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
--> type_value_check_client=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
-> '[' -n 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 ']'
-> '[' -n '' ']'
-> '[' -n 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 ']'
-> _assert_regex '[0-9A-Za-z_-]+' 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
-> declare 'pattern=[0-9A-Za-z_-]+' string=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
-> [[ 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 =~ [0-9A-Za-z_-]+ ]]
-> return 0
-> '[' -n '' ']'
-> valid_check_client=true
-> continue
-> '[' -n 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 ']'
-> '[' -n true ']'
-> _set_value direct ACCOUNT_backup_CLIENT_SECRET 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
-> case "${1:?}" in
-> export ACCOUNT_backup_CLIENT_SECRET=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
-> ACCOUNT_backup_CLIENT_SECRET=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
-> _set_value direct CLIENT_SECRET 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
-> case "${1:?}" in
-> export CLIENT_SECRET=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
-> CLIENT_SECRET=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
-> return 0
-> _check_refresh_token backup
-> export CLIENT_ID CLIENT_SECRET QUIET CONFIG CURL_PROGRESS SCOPE REDIRECT_URI TOKEN_URL
-> '[' -z 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 ']'
-> account_name_check_refresh_token=backup
-> refresh_token_regex='[0-9]//[0-9A-Za-z_-]+'
-> authorization_code_regex='[0-9]/[0-9A-Za-z_-]+'
-> _set_value direct refresh_token_name_check_refresh_token ACCOUNT_backup_REFRESH_TOKEN
-> case "${1:?}" in
-> export refresh_token_name_check_refresh_token=ACCOUNT_backup_REFRESH_TOKEN
-> refresh_token_name_check_refresh_token=ACCOUNT_backup_REFRESH_TOKEN
-> _set_value indirect refresh_token_value_check_refresh_token ACCOUNT_backup_REFRESH_TOKEN
-> case "${1:?}" in
-> eval export 'refresh_token_value_check_refresh_token="$ACCOUNT_backup_REFRESH_TOKEN"'
--> export refresh_token_value_check_refresh_token=
--> refresh_token_value_check_refresh_token=
-> '[' false = true ']'
-> '[' -n '' ']'
-> '[' -z '' ']'
-> printf '\n'
-> _print_center normal 'If you have a refresh token generated, then type the token, else leave blank and press return key..' ' '
-> '[' 3 = 3 ']'
-> printf '%s\n' 'If you have a refresh token generated, then type the token, else leave blank and press return key..'
If you have a refresh token generated, then type the token, else leave blank and press return key..
-> printf '\n'
-> _print_center normal ' Refresh Token ' -
-> '[' 3 = 3 ']'
-> printf '%s\n' ' Refresh Token '
 Refresh Token
-> printf -- '-> '
-> -> read -r refresh_token_value_check_refresh_token
-> '[' -n '' ']'
-> _print_center normal ' No Refresh token given, follow below steps to generate.. ' -
-> '[' 3 = 3 ']'
-> printf '%s\n' ' No Refresh token given, follow below steps to generate.. '
 No Refresh token given, follow below steps to generate..
-> unset refresh_token_value_check_refresh_token
-> server_string_check_refresh_token='Now go back to command line..'
-> server_port_check_refresh_token=8079
-> :
-> : 8080
-> '[' 8080 -gt 8130 ']'
-> curl -Is http://localhost:8080
-> break
-> command -v python
-> python -V
-> grep -q 'Python 3'
-> _tmp_server_pid=11789
-> python
--> _epoch
--> printf '%(%s)T\n' -1
-> code_challenge_check_refresh_token=1658613366authorization_code
-> '[' -z '' ']'
-> printf '\n'
-> _print_center normal 'Visit the below URL, follow the instructions and then come back to commandline' ' '
-> '[' 3 = 3 ']'
-> printf '%s\n' 'Visit the below URL, follow the instructions and then come back
to commandline'
Visit the below URL, follow the instructions and then come back to commandline
-> URL='https://accounts.google.com/o/oauth2/auth?client_id=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com&redirect_uri=http%3A//localhost%3A8080&scope=https://www.googleapis.com/auth/drive&response_type=code&code_challenge_method=plain&code_challenge=1658613366authorization_code'
-> printf '\n%s\n' 'https://accounts.google.com/o/oauth2/auth?client_id=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com&redirect_uri=http%3A//localhost%3A8080&scope=https://www.googleapis.com/auth/drive&response_type=code&code_challenge_method=plain&code_challenge=1658613366authorization_code'
https://accounts.google.com/o/oauth2/auth?client_id=903443719886-9fbj54b72de0u18ci6pe2fqg2rnka3pi.apps.googleusercontent.com&redirect_uri=http%3A//localhost%3A8080&scope=https://www.googleapis.com/auth/drive&response_type=code&code_challenge_method=plain&code_challenge=1658613366authorization_code
-> _print_center normal ' Press enter if you have completed the process in browser' -
-> '[' 3 = 3 ']'
-> printf '%s\n' ' Press enter if you have completed the process in browser'
 Press enter if you have completed the process in browser
-> read -r _
-> kill 11789
--> grep -m1 'GET.*code.*HTTP/1.1'
--> sed -e 's/.*GET.*code=//' -e 's/\&.*//'
-> authorization_code=
-> _assert_regex '[0-9]/[0-9A-Za-z_-]+' ''
/home/pi/.google-drive-upload/bin/gupload: line 5: 2: Missing string
-> _cleanup
-> '[' -n '' ']'
-> return 0
pi@raspberrypi:~ $
```

**Comment by Akianonymus** [comment]
I don't see the `ERR_CONNECTION_REFUSED` in logs as you said before

It is creating a localhost server to grab the code from the browser.

I will give you a new script with more debug options soon, for now run this python script and see if server is started successfully or not.

```python
from http.server import BaseHTTPRequestHandler, HTTPServer


class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        if "/?code" in self.path:
            message = "Go back to command line"
            self.wfile.write(bytes(message, "utf8"))


with HTTPServer(("", 8080), handler) as server:
    server.handle_request()
```

Copy this to a file, let's say a.py

then, python a.py, a http server should

Visit http://localhost:8080/?code=4/0AdQt8qi-y9VMjWL7SQAxdxlbvDZr9S6NN8gqE8_9LupN4R3Cvp-r5Vc0U2VE1hSy0cZoRQ&scope=https://www.googleapis.com/auth/drive and see if a page appears in browser. Also see what is the output of the python script after visiting the url.

**Comment by Roei639** [comment]
log a.py:
```Traceback (most recent call last):
  File "/home/pi/a.py", line 13, in <module>
    with HTTPServer(("", 8080), handler) as server:
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

1. I changed port 8080 to port 9797 and the a.py script seems to work
2. I replaced localhost with my pi address
3. I was able to access from a browser the address you sent in the following format: 
```http://192.168.1.253:9797/?code=4/0AdQt8qi-y9VMjWL7SQAxdxlbvDZr9S6NN8gqE8_9LupN4R3Cvp-r5Vc0U2VE1hSy0cZoRQ&scope=https://www.googleapis.com/auth/drive```

How do we continue from here?

**Comment by Akianonymus** [comment]
You were not able to open with localhost ?

**Comment by Roei639** [comment]
No...

**Comment by nextvern** [comment]
I have same problem on v4.5. I think python http server is not working.

**Comment by jkaan** [comment]
Same issue here!

**Comment by mohamed-tayeh** [comment]
~~It works for me and I get the the token after `?code=` until `&` however when I paste in the command line, it doesn't work "Invalid refresh token".~~

I figured it out:
- Follow the download steps in the [Installation](https://labbots.github.io/google-drive-upload/setup/install/) and the  [Initial Setup](https://labbots.github.io/google-drive-upload/setup/initial_setup/)
- When prompted to go to the URL:
1. Go to URL
2. Keep clicking ok and login - if you see unauthorized click on go to site at the bottom left of the page, continue until the localhost page
3. If you are doing this from a VM, change `localhost` in the URL to the IP address of the VM (this was the issue for me since I wasn't setting it up on my computer but on a VM so localhost would point to my computer instead of the VM)
4. You should see the message prompt to back to CLI (you don't need to copy paste anything)
5. In the CLI, press enter
6. Setup the root folder for when uploading to Google Drive

Complete 🚀

I would have appreciated if it was specifically stated to go to the IP address of the VM instead of localhost:) Hope this helps someone who is also new to bash scripts
